# Generated by Django 4.1 on 2022-08-19 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(help_text='Enter the body of the blogpost', max_length=255, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 19, 18, 37, 15, 481632, tzinfo=datetime.timezone.utc), help_text='Enter the publication date', verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Enter the title', max_length=20, verbose_name='Title'),
        ),
    ]
