# Generated by Django 4.1 on 2022-08-23 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_likes_blog_user_alter_blog_blog_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 23, 2, 31, 15, 452948, tzinfo=datetime.timezone.utc), help_text='Enter the publication date', verbose_name='Publication date'),
        ),
    ]
